#!/usr/bin/env node
/**
 * Reads content/pattern-library.md and writes it as a TS string export to
 * src/lib/generated/pattern-library.ts.
 *
 * Runs automatically on `predev` and `prebuild`. This avoids relying on
 * `fs.readFileSync` at runtime, so the library ships with the bundle and
 * works on any Next.js runtime (Node or Edge) without file-tracing config.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const src = path.join(root, "content", "pattern-library.md");
const out = path.join(root, "src", "lib", "generated", "pattern-library.ts");

if (!fs.existsSync(src)) {
  console.error(`[embed-library] ERROR: ${src} not found`);
  process.exit(1);
}

const md = fs.readFileSync(src, "utf8");

// Use backticks + escape backticks and ${ inside
const escaped = md.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const banner = `// AUTO-GENERATED by scripts/embed-library.mjs — DO NOT EDIT BY HAND.
// Regenerate: npm run embed  (also runs on predev / prebuild)
// Source: content/pattern-library.md
`;

const body = `${banner}\nexport const PATTERN_LIBRARY: string = \`${escaped}\`;\n`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body, "utf8");

const bytes = Buffer.byteLength(md, "utf8");
console.log(
  `[embed-library] embedded ${bytes.toLocaleString()} bytes from content/pattern-library.md -> src/lib/generated/pattern-library.ts`,
);
